---
title: "trend_anal"
author: "Sonya Havens"
date: "2022-09-29"
output: html_document:
  keep.md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load_packages, include = FALSE}
library(tidyverse)
library(janitor)
library(here)
library(ggridges)
library(viridis)
library(viridisLite)
library(patchwork)
library(ggrepel)
library(lubridate)
```

```{r source_themes, include = FALSE}
source(here("functions", "theme_SH_pubs.R"))
```

```{r load_dbase_data}
LTER_dbase_orig <- read_csv(here("data", "LTER_chem_1968to2017.csv"))

glimpse(LTER_dbase_orig)
```

```{r clean_dbase_data}
LTER_dbase_clean <- LTER_dbase_orig %>% 
  clean_names() %>% 
  rename(nh3n = nh4) %>% 
  rename(partc = suspc) %>% 
  rename(partn = suspn) %>% 
  rename(partp = suspp) %>% 
  rename(partfe = susfe) %>% 
  rename(ph = elaph) %>% 
  rename(dic = eladic) %>% 
  rename(no2n = no2) %>% 
  rename(no3n = no3) %>% 
  rename(sample_number = number) %>% 
  rename(collect_date = sampled)

glimpse(LTER_dbase_clean)
```

```{r rearrange_dbase_data}
 
LTER_dbase_long <- LTER_dbase_clean %>% 
  pivot_longer(cols = c(-sample_number, -collect_date, -year, -type, -location, -subloc, -station, -depth), names_to = "parameter", values_to = "result") %>% 

# combine location, subloc, station, and depth into one, separated by a space, and make new column called site

  mutate(site = str_c(location, subloc, station, depth, sep = " ")) %>% 
  
# convert sample date to julian date and create a new julian date column
  
  mutate(julian = yday(collect_date))

print(LTER_dbase_long)
```

```{r extracted_dbase_dataframe}

LTER_dbase <- LTER_dbase_long %>% 
  select(sample_number, collect_date, year, julian, site, parameter, result)

glimpse(LTER_dbase)
```


```{r load_SM_data}

LTER_2017_orig <- read_csv(here("data", "2017_LTER_data.csv"))
clean_names() %>% 
  rename(parameter = param) %>% 
  rename(result = numeric_result)


LTER_2018_orig <- read_csv(here("data", "2018_LTER_data.csv"))
LTER_2019_orig <- read_csv(here("data", "2019_LTER_data.csv"))
LTER_2020_orig <- read_csv(here("data", "2020_LTER_data.csv"))
LTER_2021_orig <- read_csv(here("data", "2021_LTER_data.csv"))
LTER_2022_orig <- read_csv(here("data", "2022_LTER_data.csv"))

```

```{r clean_extract_SM}

LTER_2017_clean <- LTER_2017_orig %>% 
  clean_names() %>% 
  rename(parameter = param) %>% 
  rename(result = numeric_result)
  
LTER_2017 <- LTER_2017_clean %>% 
  select(sample_number, collect_date, site, parameter, result)


LTER_2018_clean <- LTER_2018_orig %>% 
  clean_names() %>% 
  rename(parameter = param) %>% 
  rename(result = numeric_result)
  
LTER_2018 <- LTER_2018_clean %>% 
  select(sample_number, collect_date, site, parameter, result)


LTER_2019_clean <- LTER_2019_orig %>% 
  clean_names() %>% 
  rename(parameter = param) %>% 
  rename(result = numeric_result)
  
LTER_2019 <- LTER_2019_clean %>% 
  select(sample_number, collect_date, site, parameter, result)


LTER_2020_clean <- LTER_2020_orig %>% 
  clean_names() %>% 
  rename(parameter = param) %>% 
  rename(result = numeric_result)
  
LTER_2020 <- LTER_2020_clean %>% 
  select(sample_number, collect_date, site, parameter, result)


LTER_2021_clean <- LTER_2021_orig %>% 
  clean_names() %>% 
  rename(parameter = param) %>% 
  rename(result = numeric_result)
  
LTER_2021 <- LTER_2021_clean %>% 
  select(sample_number, collect_date, site, parameter, result)


LTER_2022_clean <- LTER_2022_orig %>% 
  clean_names() %>% 
  rename(parameter = param) %>% 
  rename(result = numeric_result)
  
LTER_2022 <- LTER_2022_clean %>% 
  select(sample_number, collect_date, site, parameter, result)

```


```{r merge_SM_datasets}

LTER_SM_merged <- bind_rows(lst(LTER_2017, LTER_2018, LTER_2019, LTER_2020, LTER_2021, LTER_2022), .id = "batch")

glimpse(LTER_SM_merged)

```

```{r clean_param_names}

LTER_SM_merged %>% 
  mutate(parameter = tolower(parameter))

LTER_SM_clean <- LTER_SM_merged %>% 
  rename(nh3n = nh3-n) %>% 
  rename(no3n = no3-n) %>% 
  rename(no2n = no2-n) # %>% 
  # rename(partc = part c) %>% 
  # rename(partn = part n) %>% 
  # rename(partp = part p) %>% 
  # rename(partfe = part fe)
```



```{r rearrange_SM_data}
  
# extract year from collect date and create new column called year
  
LTER_SM_clean %>% 
  mutate(collect_date = mdy(collect_date)) %>% 
  mutate(year = year(collect_date)) %>% 
  
  # convert sample date to julian date and create a new julian date column
  
  mutate(julian = yday(collect_date)) %>% 
  mutate(parameter = tolower(parameter))

print(LTER_SM_clean)
```

```{r extract_SM_dataframe}

LTER_SM <- LTER_SM_clean %>% 
  data[ , c("sample_number", "collect_date", "year", "julian", "site", "parameter", "result")]

```


```{r merged_dbase_SM}

LTER_merged <- bind_rows(lst(LTER_dbase, LTER_SM), .id = "batch")

```


Would like to plot julian date vs results, grouped by year, facet wrapped by parameter
```{r plot}
# want to graph julian day vs result for each site/parameter combination, with each year being a different plot

LTER_merged %>% 

  ggplot() +
  facet_wrap(~ site + parameter) +
  # or would facet_grid be better
  #  facet_grid(rows = vars(parameter), cols = vars(site)) +
  group_by(year) +  
  geom_point(aes(x = julian, y = result, colour = year)) +
  geom_path(aes(x = julian, y = result, colour = year)) +
  theme_SH_pubs() +
  scale_color_viridis()


#  geom_point(aes(x = samp_date_time, y = concentration, colour = compound)) +
#  geom_smooth(aes(x = samp_date_time, y = concentration, colour = compound, fill = compound)) +
#  scale_x_datetime(date_breaks  = "3 months", date_labels = "%b") +
#  theme_pepe() +
#  labs(x = NULL,
#       y = "Concentration (mg/L)")
  
ggsave(here("figures", "trend_anal_2022.pdf"), trend_anal_2022,
       width = 190, height = 120, units = "mm")
```


```{r timestamp}
str_c("This report was created on", Sys.Date(), sep = " ")
```

